### ISSUE TITLE
--dry-run option has a separate implementation

### ISSUE THREAD

**Issue by jandubois** [spinframework/spin-plugin-kube#95]
As #93 has shown, the manifest generated by `spin kube deploy --dry-run` does not necessarily match the manifest applied by `spin kube deploy`.

One of the main reasons to have a `--dry-run` option is to be able to see what will happen if you let the tool execute the command automatically (e.g. to debug why the tool is not doing what you think it does).

Having separate codepaths for generating the `--dry-run` output kind of negates this purpose because the implementations can diverge (as has been the case in #93).

So I think the plugin should marshal the configuration generated with the help of the spin operator code into YAML to implement the `--dry-run` functionality, or alternatively construct the YAML document, and then unmarshal it internally to deploy.

**Comment by rajatjindal** [comment]
Hi @jandubois

just to confirm, did you try `spin kube deploy --dry-run` and `spin kube deploy` OR by any chance you had tried `spin kube scaffold --dry-run` and then `spin kube deploy`. 

in anycase we should update `spin kube deploy` to use same scaffolding as `spin kube scaffold`.

**Comment by jandubois** [comment]
This worked:

```
spin kube deploy --dry-run --from ghcr.io/spinkube/containerd-shim-spin/examples/spin-rust-hello:v0.13.0 | kubectl apply -f -
```

and this one didn't (see #93):

```
spin kube deploy --from ghcr.io/spinkube/containerd-shim-spin/examples/spin-rust-hello:v0.13.0
```

The `--dry-run` version is using `core.spinkube.dev` and the other version is using `core.spinoperator.dev` because it uses "github.com/spinkube/spin-operator v0.1.0" to create the manifest.

**Comment by rajatjindal** [comment]
thank you for providing additional context. its super helpful.

**Comment by Mossaka** [comment]
I believe this issue has been resolved already.

```
spin kube deploy --dry-run --from ghcr.io/spinkube/containerd-shim-spin/examples/spin-rust-hello:v0.13.0
apiVersion: core.spinkube.dev/v1alpha1
kind: SpinApp
metadata:
  creationTimestamp: null
  name: spin-rust-hello
  namespace: default
spec:
  checks: {}
  executor: containerd-shim-spin
  image: ghcr.io/spinkube/containerd-shim-spin/examples/spin-rust-hello:v0.13.0
  replicas: 2
  resources: {}
  runtimeConfig: {}
status:
  readyReplicas: 0
```

and

```
spin kube deploy --from ghcr.io/spinkube/containerd-shim-spin/examples/spin-rust-hello:v0.13.0    
spinapp.spin.fermyon.com/spin-rust-hello configured

k describe spinapp spin-rust-hello                                                             
Name:         spin-rust-hello
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  core.spinkube.dev/v1alpha1
Kind:         SpinApp
```
